[env:esp32dev]
platform = espressif32
board = esp32dev
framework = arduino
monitor_speed = 115200
upload_speed = 921600

; Vestavěné knihovny Arduino core (SD, WiFi, FS) + volitelná SPI
lib_deps =

build_flags =
  -DCORE_DEBUG_LEVEL=1
  -DESP_OS_VERSION=\"0.0.1\"
  -DLUA_USE_C89
  -DLUA_COMPAT_5_3
  -Ilib/lua/src

lib_ldf_mode = deep+
